name = "my-app"
compatibility_date = "2024-08-31"

# [vars]
# MY_VAR = "my-variable"

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjU0N2YyMzgtMTE1NS00NzAxLThiYTgtZjNmNTg0YWJhNzEwIiwidGVuYW50X2lkIjoiNGM2MzRlMjZjMDUyNTJhY2IwZmIyMGFmZTQ0ODA2ZGVlYTQxMzIwNTcwNmMwNTJlYTk0ZDUzNzhkYWM5YTJiYSIsImludGVybmFsX3NlY3JldCI6IjEyZWNjZDM2LTExNjEtNDZlOS04Y2VlLWNmN2RiZWQxNmY1NSJ9.Z7Qbrhx9uAczCI5SCwcH1rOt8PbkU15sbSeRDIB22Qk"