name = "my-app"
compatibility_date = "2024-08-31"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWQ5YjNjODAtYzU2Mi00Y2YzLWJiNTctNDZiMDNmMTAxNDZiIiwidGVuYW50X2lkIjoiZjI5NzZjOWMwZGM5N2RlNGUyYjNjZDM4MWNjNzliYTY5OGZiZjg5Yzc0NjYzNTA3ZjFkMzY3NWIyZDA3ZWQ2MCIsImludGVybmFsX3NlY3JldCI6IjM2YmJkZjliLTVmOTAtNGE0Zi05YjViLTEzYjVlMDc0NmQ1OCJ9.CDAhs82lAlLYSWGSZxPOecdStVPEsKDsWSwYMMJeyEg"

JWT_SECRET = "shieuf45"








